using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace RippleTrade_DB
{
    /// <summary>
    /// Controller class for API_Calls
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ApiCallController
    {
        // Preload our schema..
        ApiCall thisSchemaLoad = new ApiCall();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ApiCallCollection FetchAll()
        {
            ApiCallCollection coll = new ApiCallCollection();
            Query qry = new Query(ApiCall.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ApiCallCollection FetchByID(object ApiCallKey)
        {
            ApiCallCollection coll = new ApiCallCollection().Where("api_call_key", ApiCallKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ApiCallCollection FetchByQuery(Query qry)
        {
            ApiCallCollection coll = new ApiCallCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ApiCallKey)
        {
            return (ApiCall.Delete(ApiCallKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ApiCallKey)
        {
            return (ApiCall.Destroy(ApiCallKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? TxKey,string Request,string Response,string Url,DateTime? Dateoccured)
	    {
		    ApiCall item = new ApiCall();
		    
            item.TxKey = TxKey;
            
            item.Request = Request;
            
            item.Response = Response;
            
            item.Url = Url;
            
            item.Dateoccured = Dateoccured;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int ApiCallKey,int? TxKey,string Request,string Response,string Url,DateTime? Dateoccured)
	    {
		    ApiCall item = new ApiCall();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ApiCallKey = ApiCallKey;
				
			item.TxKey = TxKey;
				
			item.Request = Request;
				
			item.Response = Response;
				
			item.Url = Url;
				
			item.Dateoccured = Dateoccured;
				
	        item.Save(UserName);
	    }
    }
}
