using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace RippleTrade_DB
{
	/// <summary>
	/// Strongly-typed collection for the ApiCall class.
	/// </summary>
    [Serializable]
	public partial class ApiCallCollection : ActiveList<ApiCall, ApiCallCollection>
	{	   
		public ApiCallCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>ApiCallCollection</returns>
		public ApiCallCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                ApiCall o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the API_Calls table.
	/// </summary>
	[Serializable]
	public partial class ApiCall : ActiveRecord<ApiCall>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public ApiCall()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public ApiCall(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public ApiCall(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public ApiCall(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("API_Calls", TableType.Table, DataService.GetInstance("RippleTrade"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarApiCallKey = new TableSchema.TableColumn(schema);
				colvarApiCallKey.ColumnName = "api_call_key";
				colvarApiCallKey.DataType = DbType.Int32;
				colvarApiCallKey.MaxLength = 0;
				colvarApiCallKey.AutoIncrement = true;
				colvarApiCallKey.IsNullable = false;
				colvarApiCallKey.IsPrimaryKey = true;
				colvarApiCallKey.IsForeignKey = false;
				colvarApiCallKey.IsReadOnly = false;
				colvarApiCallKey.DefaultSetting = @"";
				colvarApiCallKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarApiCallKey);
				
				TableSchema.TableColumn colvarTxKey = new TableSchema.TableColumn(schema);
				colvarTxKey.ColumnName = "tx_key";
				colvarTxKey.DataType = DbType.Int32;
				colvarTxKey.MaxLength = 0;
				colvarTxKey.AutoIncrement = false;
				colvarTxKey.IsNullable = true;
				colvarTxKey.IsPrimaryKey = false;
				colvarTxKey.IsForeignKey = false;
				colvarTxKey.IsReadOnly = false;
				colvarTxKey.DefaultSetting = @"";
				colvarTxKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTxKey);
				
				TableSchema.TableColumn colvarRequest = new TableSchema.TableColumn(schema);
				colvarRequest.ColumnName = "request";
				colvarRequest.DataType = DbType.AnsiString;
				colvarRequest.MaxLength = 2147483647;
				colvarRequest.AutoIncrement = false;
				colvarRequest.IsNullable = true;
				colvarRequest.IsPrimaryKey = false;
				colvarRequest.IsForeignKey = false;
				colvarRequest.IsReadOnly = false;
				colvarRequest.DefaultSetting = @"";
				colvarRequest.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRequest);
				
				TableSchema.TableColumn colvarResponse = new TableSchema.TableColumn(schema);
				colvarResponse.ColumnName = "response";
				colvarResponse.DataType = DbType.AnsiString;
				colvarResponse.MaxLength = 2147483647;
				colvarResponse.AutoIncrement = false;
				colvarResponse.IsNullable = true;
				colvarResponse.IsPrimaryKey = false;
				colvarResponse.IsForeignKey = false;
				colvarResponse.IsReadOnly = false;
				colvarResponse.DefaultSetting = @"";
				colvarResponse.ForeignKeyTableName = "";
				schema.Columns.Add(colvarResponse);
				
				TableSchema.TableColumn colvarUrl = new TableSchema.TableColumn(schema);
				colvarUrl.ColumnName = "url";
				colvarUrl.DataType = DbType.AnsiString;
				colvarUrl.MaxLength = 100;
				colvarUrl.AutoIncrement = false;
				colvarUrl.IsNullable = true;
				colvarUrl.IsPrimaryKey = false;
				colvarUrl.IsForeignKey = false;
				colvarUrl.IsReadOnly = false;
				colvarUrl.DefaultSetting = @"";
				colvarUrl.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUrl);
				
				TableSchema.TableColumn colvarDateoccured = new TableSchema.TableColumn(schema);
				colvarDateoccured.ColumnName = "dateoccured";
				colvarDateoccured.DataType = DbType.DateTime;
				colvarDateoccured.MaxLength = 0;
				colvarDateoccured.AutoIncrement = false;
				colvarDateoccured.IsNullable = true;
				colvarDateoccured.IsPrimaryKey = false;
				colvarDateoccured.IsForeignKey = false;
				colvarDateoccured.IsReadOnly = false;
				colvarDateoccured.DefaultSetting = @"";
				colvarDateoccured.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDateoccured);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["RippleTrade"].AddSchema("API_Calls",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("ApiCallKey")]
		[Bindable(true)]
		public int ApiCallKey 
		{
			get { return GetColumnValue<int>(Columns.ApiCallKey); }
			set { SetColumnValue(Columns.ApiCallKey, value); }
		}
		  
		[XmlAttribute("TxKey")]
		[Bindable(true)]
		public int? TxKey 
		{
			get { return GetColumnValue<int?>(Columns.TxKey); }
			set { SetColumnValue(Columns.TxKey, value); }
		}
		  
		[XmlAttribute("Request")]
		[Bindable(true)]
		public string Request 
		{
			get { return GetColumnValue<string>(Columns.Request); }
			set { SetColumnValue(Columns.Request, value); }
		}
		  
		[XmlAttribute("Response")]
		[Bindable(true)]
		public string Response 
		{
			get { return GetColumnValue<string>(Columns.Response); }
			set { SetColumnValue(Columns.Response, value); }
		}
		  
		[XmlAttribute("Url")]
		[Bindable(true)]
		public string Url 
		{
			get { return GetColumnValue<string>(Columns.Url); }
			set { SetColumnValue(Columns.Url, value); }
		}
		  
		[XmlAttribute("Dateoccured")]
		[Bindable(true)]
		public DateTime? Dateoccured 
		{
			get { return GetColumnValue<DateTime?>(Columns.Dateoccured); }
			set { SetColumnValue(Columns.Dateoccured, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varTxKey,string varRequest,string varResponse,string varUrl,DateTime? varDateoccured)
		{
			ApiCall item = new ApiCall();
			
			item.TxKey = varTxKey;
			
			item.Request = varRequest;
			
			item.Response = varResponse;
			
			item.Url = varUrl;
			
			item.Dateoccured = varDateoccured;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varApiCallKey,int? varTxKey,string varRequest,string varResponse,string varUrl,DateTime? varDateoccured)
		{
			ApiCall item = new ApiCall();
			
				item.ApiCallKey = varApiCallKey;
			
				item.TxKey = varTxKey;
			
				item.Request = varRequest;
			
				item.Response = varResponse;
			
				item.Url = varUrl;
			
				item.Dateoccured = varDateoccured;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn ApiCallKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TxKeyColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn RequestColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ResponseColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn UrlColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn DateoccuredColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string ApiCallKey = @"api_call_key";
			 public static string TxKey = @"tx_key";
			 public static string Request = @"request";
			 public static string Response = @"response";
			 public static string Url = @"url";
			 public static string Dateoccured = @"dateoccured";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
