using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace RippleTrade_DB
{
	/// <summary>
	/// Strongly-typed collection for the ExchangeCurrency class.
	/// </summary>
    [Serializable]
	public partial class ExchangeCurrencyCollection : ActiveList<ExchangeCurrency, ExchangeCurrencyCollection>
	{	   
		public ExchangeCurrencyCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>ExchangeCurrencyCollection</returns>
		public ExchangeCurrencyCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                ExchangeCurrency o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Exchange_Currency table.
	/// </summary>
	[Serializable]
	public partial class ExchangeCurrency : ActiveRecord<ExchangeCurrency>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public ExchangeCurrency()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public ExchangeCurrency(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public ExchangeCurrency(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public ExchangeCurrency(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Exchange_Currency", TableType.Table, DataService.GetInstance("RippleTrade"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarExchangeCurrencyKey = new TableSchema.TableColumn(schema);
				colvarExchangeCurrencyKey.ColumnName = "exchange_currency_key";
				colvarExchangeCurrencyKey.DataType = DbType.Int32;
				colvarExchangeCurrencyKey.MaxLength = 0;
				colvarExchangeCurrencyKey.AutoIncrement = false;
				colvarExchangeCurrencyKey.IsNullable = false;
				colvarExchangeCurrencyKey.IsPrimaryKey = true;
				colvarExchangeCurrencyKey.IsForeignKey = false;
				colvarExchangeCurrencyKey.IsReadOnly = false;
				colvarExchangeCurrencyKey.DefaultSetting = @"";
				colvarExchangeCurrencyKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarExchangeCurrencyKey);
				
				TableSchema.TableColumn colvarExchangeKey = new TableSchema.TableColumn(schema);
				colvarExchangeKey.ColumnName = "exchange_key";
				colvarExchangeKey.DataType = DbType.Int32;
				colvarExchangeKey.MaxLength = 0;
				colvarExchangeKey.AutoIncrement = false;
				colvarExchangeKey.IsNullable = false;
				colvarExchangeKey.IsPrimaryKey = false;
				colvarExchangeKey.IsForeignKey = false;
				colvarExchangeKey.IsReadOnly = false;
				colvarExchangeKey.DefaultSetting = @"";
				colvarExchangeKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarExchangeKey);
				
				TableSchema.TableColumn colvarCurrency = new TableSchema.TableColumn(schema);
				colvarCurrency.ColumnName = "currency";
				colvarCurrency.DataType = DbType.Int32;
				colvarCurrency.MaxLength = 0;
				colvarCurrency.AutoIncrement = false;
				colvarCurrency.IsNullable = false;
				colvarCurrency.IsPrimaryKey = false;
				colvarCurrency.IsForeignKey = false;
				colvarCurrency.IsReadOnly = false;
				colvarCurrency.DefaultSetting = @"";
				colvarCurrency.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCurrency);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["RippleTrade"].AddSchema("Exchange_Currency",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("ExchangeCurrencyKey")]
		[Bindable(true)]
		public int ExchangeCurrencyKey 
		{
			get { return GetColumnValue<int>(Columns.ExchangeCurrencyKey); }
			set { SetColumnValue(Columns.ExchangeCurrencyKey, value); }
		}
		  
		[XmlAttribute("ExchangeKey")]
		[Bindable(true)]
		public int ExchangeKey 
		{
			get { return GetColumnValue<int>(Columns.ExchangeKey); }
			set { SetColumnValue(Columns.ExchangeKey, value); }
		}
		  
		[XmlAttribute("Currency")]
		[Bindable(true)]
		public int Currency 
		{
			get { return GetColumnValue<int>(Columns.Currency); }
			set { SetColumnValue(Columns.Currency, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varExchangeCurrencyKey,int varExchangeKey,int varCurrency)
		{
			ExchangeCurrency item = new ExchangeCurrency();
			
			item.ExchangeCurrencyKey = varExchangeCurrencyKey;
			
			item.ExchangeKey = varExchangeKey;
			
			item.Currency = varCurrency;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varExchangeCurrencyKey,int varExchangeKey,int varCurrency)
		{
			ExchangeCurrency item = new ExchangeCurrency();
			
				item.ExchangeCurrencyKey = varExchangeCurrencyKey;
			
				item.ExchangeKey = varExchangeKey;
			
				item.Currency = varCurrency;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn ExchangeCurrencyKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ExchangeKeyColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn CurrencyColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string ExchangeCurrencyKey = @"exchange_currency_key";
			 public static string ExchangeKey = @"exchange_key";
			 public static string Currency = @"currency";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
