using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace RippleTrade_DB{
    public partial class SPs{
        
        /// <summary>
        /// Creates an object wrapper for the Delete_Markets_All Procedure
        /// </summary>
        public static StoredProcedure DeleteMarketsAll()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Delete_Markets_All", DataService.GetInstance("RippleTrade"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Delete_Path Procedure
        /// </summary>
        public static StoredProcedure DeletePath(int? pathkey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Delete_Path", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@path_key", pathkey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Delete_Path_Route Procedure
        /// </summary>
        public static StoredProcedure DeletePathRoute(int? pathroutekey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Delete_Path_Route", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@path_route_key", pathroutekey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Delete_Path_Routes_All Procedure
        /// </summary>
        public static StoredProcedure DeletePathRoutesAll()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Delete_Path_Routes_All", DataService.GetInstance("RippleTrade"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Update_CurrencyCloud_Tokens Procedure
        /// </summary>
        public static StoredProcedure UpdateCurrencyCloudTokens(int? cctokenkey, string cctoken)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Update_CurrencyCloud_Tokens", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@cctokenkey", cctokenkey, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@cctoken", cctoken, DbType.AnsiString, null, null);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Update_Exchange_Rates Procedure
        /// </summary>
        public static StoredProcedure UpdateExchangeRates(int? exchangeratekey, decimal? exchangerate)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Update_Exchange_Rates", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@exchange_rate_key", exchangeratekey, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@exchange_rate", exchangerate, DbType.Currency, 4, 19);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Update_MarketData Procedure
        /// </summary>
        public static StoredProcedure UpdateMarketData(string price, string volume, int? marketkey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Update_MarketData", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@price", price, DbType.AnsiString, null, null);
        	
            sp.Command.AddParameter("@volume", volume, DbType.AnsiString, null, null);
        	
            sp.Command.AddParameter("@market_key", marketkey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Update_Markets Procedure
        /// </summary>
        public static StoredProcedure UpdateMarkets(int? source, int? destination)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Update_Markets", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@source", source, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@destination", destination, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Update_Path Procedure
        /// </summary>
        public static StoredProcedure UpdatePath(int? pathkey, int? pageorder)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Update_Path", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@path_key", pathkey, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@page_order", pageorder, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the Update_Path_Route Procedure
        /// </summary>
        public static StoredProcedure UpdatePathRoute(int? pathroutekey, int? pathkey, int? marketkey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("Update_Path_Route", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@path_route_key", pathroutekey, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@path_key", pathkey, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@market_key", marketkey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Exchange_Currencies_All Procedure
        /// </summary>
        public static StoredProcedure ViewExchangeCurrenciesAll()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Exchange_Currencies_All", DataService.GetInstance("RippleTrade"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Exchange_Currencies_SpecificExchange Procedure
        /// </summary>
        public static StoredProcedure ViewExchangeCurrenciesSpecificExchange(int? exchangekey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Exchange_Currencies_SpecificExchange", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@exchange_key", exchangekey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Exchange_Rates Procedure
        /// </summary>
        public static StoredProcedure ViewExchangeRates(int? exchangeratekey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Exchange_Rates", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@exchange_rate_key", exchangeratekey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Exchanges_All Procedure
        /// </summary>
        public static StoredProcedure ViewExchangesAll()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Exchanges_All", DataService.GetInstance("RippleTrade"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Exchanges_OnlyAlt_All Procedure
        /// </summary>
        public static StoredProcedure ViewExchangesOnlyAltAll()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Exchanges_OnlyAlt_All", DataService.GetInstance("RippleTrade"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Info_CurrencyCloud_Tokens Procedure
        /// </summary>
        public static StoredProcedure ViewInfoCurrencyCloudTokens()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Info_CurrencyCloud_Tokens", DataService.GetInstance("RippleTrade"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Market_Data_All Procedure
        /// </summary>
        public static StoredProcedure ViewMarketDataAll()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Market_Data_All", DataService.GetInstance("RippleTrade"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Market_Data_Specific Procedure
        /// </summary>
        public static StoredProcedure ViewMarketDataSpecific(int? marketkey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Market_Data_Specific", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@market_key", marketkey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Markets_All Procedure
        /// </summary>
        public static StoredProcedure ViewMarketsAll()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Markets_All", DataService.GetInstance("RippleTrade"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Markets_Specific Procedure
        /// </summary>
        public static StoredProcedure ViewMarketsSpecific(int? marketkey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Markets_Specific", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@market_key", marketkey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Markets_Specific_byExchangeCurrencies Procedure
        /// </summary>
        public static StoredProcedure ViewMarketsSpecificByExchangeCurrencies(int? sourcecurrencykey, int? sourceexchangekey, int? destinationcurrencykey, int? destinationexchangekey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Markets_Specific_byExchangeCurrencies", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@source_currency_key", sourcecurrencykey, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@source_exchange_key", sourceexchangekey, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@destination_currency_key", destinationcurrencykey, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@destination_exchange_key", destinationexchangekey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Path_byExchanges_andCurrencies Procedure
        /// </summary>
        public static StoredProcedure ViewPathByExchangesAndCurrencies(int? exchange1, int? exchange2, int? currency1, int? currency2)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Path_byExchanges_andCurrencies", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@exchange1", exchange1, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@exchange2", exchange2, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@currency1", currency1, DbType.Int32, 0, 10);
        	
            sp.Command.AddParameter("@currency2", currency2, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Path_Route_Specific Procedure
        /// </summary>
        public static StoredProcedure ViewPathRouteSpecific(int? pathkey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Path_Route_Specific", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@path_key", pathkey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Path_Routes_All Procedure
        /// </summary>
        public static StoredProcedure ViewPathRoutesAll()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Path_Routes_All", DataService.GetInstance("RippleTrade"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Paths_All Procedure
        /// </summary>
        public static StoredProcedure ViewPathsAll()
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Paths_All", DataService.GetInstance("RippleTrade"), "");
        	
            return sp;
        }
        
        /// <summary>
        /// Creates an object wrapper for the View_Paths_WithMarket Procedure
        /// </summary>
        public static StoredProcedure ViewPathsWithMarket(int? marketkey)
        {
            SubSonic.StoredProcedure sp = new SubSonic.StoredProcedure("View_Paths_WithMarket", DataService.GetInstance("RippleTrade"), "dbo");
        	
            sp.Command.AddParameter("@market_key", marketkey, DbType.Int32, 0, 10);
        	
            return sp;
        }
        
    }
    
}
