using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
    /// <summary>
    /// Controller class for Arb_Results
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ArbResultController
    {
        // Preload our schema..
        ArbResult thisSchemaLoad = new ArbResult();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ArbResultCollection FetchAll()
        {
            ArbResultCollection coll = new ArbResultCollection();
            Query qry = new Query(ArbResult.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ArbResultCollection FetchByID(object ArbResultsKey)
        {
            ArbResultCollection coll = new ArbResultCollection().Where("arb_results_key", ArbResultsKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ArbResultCollection FetchByQuery(Query qry)
        {
            ArbResultCollection coll = new ArbResultCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ArbResultsKey)
        {
            return (ArbResult.Delete(ArbResultsKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ArbResultsKey)
        {
            return (ArbResult.Destroy(ArbResultsKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int ArbResultsKey,int StartingNode,int EndNode,decimal? Percentage,DateTime? LastChanged,int? Triptime,string Label)
	    {
		    ArbResult item = new ArbResult();
		    
            item.ArbResultsKey = ArbResultsKey;
            
            item.StartingNode = StartingNode;
            
            item.EndNode = EndNode;
            
            item.Percentage = Percentage;
            
            item.LastChanged = LastChanged;
            
            item.Triptime = Triptime;
            
            item.Label = Label;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int ArbResultsKey,int StartingNode,int EndNode,decimal? Percentage,DateTime? LastChanged,int? Triptime,string Label)
	    {
		    ArbResult item = new ArbResult();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ArbResultsKey = ArbResultsKey;
				
			item.StartingNode = StartingNode;
				
			item.EndNode = EndNode;
				
			item.Percentage = Percentage;
				
			item.LastChanged = LastChanged;
				
			item.Triptime = Triptime;
				
			item.Label = Label;
				
	        item.Save(UserName);
	    }
    }
}
