using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
	/// <summary>
	/// Strongly-typed collection for the CurrencyCloudToken class.
	/// </summary>
    [Serializable]
	public partial class CurrencyCloudTokenCollection : ActiveList<CurrencyCloudToken, CurrencyCloudTokenCollection>
	{	   
		public CurrencyCloudTokenCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>CurrencyCloudTokenCollection</returns>
		public CurrencyCloudTokenCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                CurrencyCloudToken o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the CurrencyCloud_Token table.
	/// </summary>
	[Serializable]
	public partial class CurrencyCloudToken : ActiveRecord<CurrencyCloudToken>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public CurrencyCloudToken()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public CurrencyCloudToken(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public CurrencyCloudToken(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public CurrencyCloudToken(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("CurrencyCloud_Token", TableType.Table, DataService.GetInstance("Bitcoin_Notify"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarCurrencyCloudTokensKey = new TableSchema.TableColumn(schema);
				colvarCurrencyCloudTokensKey.ColumnName = "CurrencyCloud_Tokens_Key";
				colvarCurrencyCloudTokensKey.DataType = DbType.Int32;
				colvarCurrencyCloudTokensKey.MaxLength = 0;
				colvarCurrencyCloudTokensKey.AutoIncrement = false;
				colvarCurrencyCloudTokensKey.IsNullable = false;
				colvarCurrencyCloudTokensKey.IsPrimaryKey = true;
				colvarCurrencyCloudTokensKey.IsForeignKey = false;
				colvarCurrencyCloudTokensKey.IsReadOnly = false;
				colvarCurrencyCloudTokensKey.DefaultSetting = @"";
				colvarCurrencyCloudTokensKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCurrencyCloudTokensKey);
				
				TableSchema.TableColumn colvarCurrencyCloudTokenX = new TableSchema.TableColumn(schema);
				colvarCurrencyCloudTokenX.ColumnName = "CurrencyCloud_Token";
				colvarCurrencyCloudTokenX.DataType = DbType.AnsiString;
				colvarCurrencyCloudTokenX.MaxLength = 50;
				colvarCurrencyCloudTokenX.AutoIncrement = false;
				colvarCurrencyCloudTokenX.IsNullable = true;
				colvarCurrencyCloudTokenX.IsPrimaryKey = false;
				colvarCurrencyCloudTokenX.IsForeignKey = false;
				colvarCurrencyCloudTokenX.IsReadOnly = false;
				colvarCurrencyCloudTokenX.DefaultSetting = @"";
				colvarCurrencyCloudTokenX.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCurrencyCloudTokenX);
				
				TableSchema.TableColumn colvarLastchanged = new TableSchema.TableColumn(schema);
				colvarLastchanged.ColumnName = "lastchanged";
				colvarLastchanged.DataType = DbType.DateTime;
				colvarLastchanged.MaxLength = 0;
				colvarLastchanged.AutoIncrement = false;
				colvarLastchanged.IsNullable = true;
				colvarLastchanged.IsPrimaryKey = false;
				colvarLastchanged.IsForeignKey = false;
				colvarLastchanged.IsReadOnly = false;
				colvarLastchanged.DefaultSetting = @"";
				colvarLastchanged.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLastchanged);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Bitcoin_Notify"].AddSchema("CurrencyCloud_Token",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("CurrencyCloudTokensKey")]
		[Bindable(true)]
		public int CurrencyCloudTokensKey 
		{
			get { return GetColumnValue<int>(Columns.CurrencyCloudTokensKey); }
			set { SetColumnValue(Columns.CurrencyCloudTokensKey, value); }
		}
		  
		[XmlAttribute("CurrencyCloudTokenX")]
		[Bindable(true)]
		public string CurrencyCloudTokenX 
		{
			get { return GetColumnValue<string>(Columns.CurrencyCloudTokenX); }
			set { SetColumnValue(Columns.CurrencyCloudTokenX, value); }
		}
		  
		[XmlAttribute("Lastchanged")]
		[Bindable(true)]
		public DateTime? Lastchanged 
		{
			get { return GetColumnValue<DateTime?>(Columns.Lastchanged); }
			set { SetColumnValue(Columns.Lastchanged, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varCurrencyCloudTokensKey,string varCurrencyCloudTokenX,DateTime? varLastchanged)
		{
			CurrencyCloudToken item = new CurrencyCloudToken();
			
			item.CurrencyCloudTokensKey = varCurrencyCloudTokensKey;
			
			item.CurrencyCloudTokenX = varCurrencyCloudTokenX;
			
			item.Lastchanged = varLastchanged;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varCurrencyCloudTokensKey,string varCurrencyCloudTokenX,DateTime? varLastchanged)
		{
			CurrencyCloudToken item = new CurrencyCloudToken();
			
				item.CurrencyCloudTokensKey = varCurrencyCloudTokensKey;
			
				item.CurrencyCloudTokenX = varCurrencyCloudTokenX;
			
				item.Lastchanged = varLastchanged;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn CurrencyCloudTokensKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn CurrencyCloudTokenXColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn LastchangedColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string CurrencyCloudTokensKey = @"CurrencyCloud_Tokens_Key";
			 public static string CurrencyCloudTokenX = @"CurrencyCloud_Token";
			 public static string Lastchanged = @"lastchanged";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
