using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
    /// <summary>
    /// Controller class for CurrencyCloud_Markets
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class CurrencyCloudMarketController
    {
        // Preload our schema..
        CurrencyCloudMarket thisSchemaLoad = new CurrencyCloudMarket();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CurrencyCloudMarketCollection FetchAll()
        {
            CurrencyCloudMarketCollection coll = new CurrencyCloudMarketCollection();
            Query qry = new Query(CurrencyCloudMarket.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CurrencyCloudMarketCollection FetchByID(object CurrencycloudMarketKey)
        {
            CurrencyCloudMarketCollection coll = new CurrencyCloudMarketCollection().Where("currencycloud_market_key", CurrencycloudMarketKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public CurrencyCloudMarketCollection FetchByQuery(Query qry)
        {
            CurrencyCloudMarketCollection coll = new CurrencyCloudMarketCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object CurrencycloudMarketKey)
        {
            return (CurrencyCloudMarket.Delete(CurrencycloudMarketKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object CurrencycloudMarketKey)
        {
            return (CurrencyCloudMarket.Destroy(CurrencycloudMarketKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int CurrencycloudMarketKey,int Source,int Destination,decimal FeePercentage,decimal? Rate,DateTime? Datechanged,decimal FeeStatic,int Exchangetime)
	    {
		    CurrencyCloudMarket item = new CurrencyCloudMarket();
		    
            item.CurrencycloudMarketKey = CurrencycloudMarketKey;
            
            item.Source = Source;
            
            item.Destination = Destination;
            
            item.FeePercentage = FeePercentage;
            
            item.Rate = Rate;
            
            item.Datechanged = Datechanged;
            
            item.FeeStatic = FeeStatic;
            
            item.Exchangetime = Exchangetime;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int CurrencycloudMarketKey,int Source,int Destination,decimal FeePercentage,decimal? Rate,DateTime? Datechanged,decimal FeeStatic,int Exchangetime)
	    {
		    CurrencyCloudMarket item = new CurrencyCloudMarket();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.CurrencycloudMarketKey = CurrencycloudMarketKey;
				
			item.Source = Source;
				
			item.Destination = Destination;
				
			item.FeePercentage = FeePercentage;
				
			item.Rate = Rate;
				
			item.Datechanged = Datechanged;
				
			item.FeeStatic = FeeStatic;
				
			item.Exchangetime = Exchangetime;
				
	        item.Save(UserName);
	    }
    }
}
