using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
	/// <summary>
	/// Strongly-typed collection for the CurrencyCloudMarket class.
	/// </summary>
    [Serializable]
	public partial class CurrencyCloudMarketCollection : ActiveList<CurrencyCloudMarket, CurrencyCloudMarketCollection>
	{	   
		public CurrencyCloudMarketCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>CurrencyCloudMarketCollection</returns>
		public CurrencyCloudMarketCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                CurrencyCloudMarket o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the CurrencyCloud_Markets table.
	/// </summary>
	[Serializable]
	public partial class CurrencyCloudMarket : ActiveRecord<CurrencyCloudMarket>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public CurrencyCloudMarket()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public CurrencyCloudMarket(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public CurrencyCloudMarket(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public CurrencyCloudMarket(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("CurrencyCloud_Markets", TableType.Table, DataService.GetInstance("Bitcoin_Notify"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarCurrencycloudMarketKey = new TableSchema.TableColumn(schema);
				colvarCurrencycloudMarketKey.ColumnName = "currencycloud_market_key";
				colvarCurrencycloudMarketKey.DataType = DbType.Int32;
				colvarCurrencycloudMarketKey.MaxLength = 0;
				colvarCurrencycloudMarketKey.AutoIncrement = false;
				colvarCurrencycloudMarketKey.IsNullable = false;
				colvarCurrencycloudMarketKey.IsPrimaryKey = true;
				colvarCurrencycloudMarketKey.IsForeignKey = false;
				colvarCurrencycloudMarketKey.IsReadOnly = false;
				colvarCurrencycloudMarketKey.DefaultSetting = @"";
				colvarCurrencycloudMarketKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCurrencycloudMarketKey);
				
				TableSchema.TableColumn colvarSource = new TableSchema.TableColumn(schema);
				colvarSource.ColumnName = "source";
				colvarSource.DataType = DbType.Int32;
				colvarSource.MaxLength = 0;
				colvarSource.AutoIncrement = false;
				colvarSource.IsNullable = false;
				colvarSource.IsPrimaryKey = false;
				colvarSource.IsForeignKey = false;
				colvarSource.IsReadOnly = false;
				colvarSource.DefaultSetting = @"";
				colvarSource.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSource);
				
				TableSchema.TableColumn colvarDestination = new TableSchema.TableColumn(schema);
				colvarDestination.ColumnName = "destination";
				colvarDestination.DataType = DbType.Int32;
				colvarDestination.MaxLength = 0;
				colvarDestination.AutoIncrement = false;
				colvarDestination.IsNullable = false;
				colvarDestination.IsPrimaryKey = false;
				colvarDestination.IsForeignKey = false;
				colvarDestination.IsReadOnly = false;
				colvarDestination.DefaultSetting = @"";
				colvarDestination.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDestination);
				
				TableSchema.TableColumn colvarFeePercentage = new TableSchema.TableColumn(schema);
				colvarFeePercentage.ColumnName = "fee_percentage";
				colvarFeePercentage.DataType = DbType.Decimal;
				colvarFeePercentage.MaxLength = 0;
				colvarFeePercentage.AutoIncrement = false;
				colvarFeePercentage.IsNullable = false;
				colvarFeePercentage.IsPrimaryKey = false;
				colvarFeePercentage.IsForeignKey = false;
				colvarFeePercentage.IsReadOnly = false;
				colvarFeePercentage.DefaultSetting = @"";
				colvarFeePercentage.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFeePercentage);
				
				TableSchema.TableColumn colvarRate = new TableSchema.TableColumn(schema);
				colvarRate.ColumnName = "rate";
				colvarRate.DataType = DbType.Currency;
				colvarRate.MaxLength = 0;
				colvarRate.AutoIncrement = false;
				colvarRate.IsNullable = true;
				colvarRate.IsPrimaryKey = false;
				colvarRate.IsForeignKey = false;
				colvarRate.IsReadOnly = false;
				colvarRate.DefaultSetting = @"";
				colvarRate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRate);
				
				TableSchema.TableColumn colvarDatechanged = new TableSchema.TableColumn(schema);
				colvarDatechanged.ColumnName = "datechanged";
				colvarDatechanged.DataType = DbType.DateTime;
				colvarDatechanged.MaxLength = 0;
				colvarDatechanged.AutoIncrement = false;
				colvarDatechanged.IsNullable = true;
				colvarDatechanged.IsPrimaryKey = false;
				colvarDatechanged.IsForeignKey = false;
				colvarDatechanged.IsReadOnly = false;
				colvarDatechanged.DefaultSetting = @"";
				colvarDatechanged.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDatechanged);
				
				TableSchema.TableColumn colvarFeeStatic = new TableSchema.TableColumn(schema);
				colvarFeeStatic.ColumnName = "fee_static";
				colvarFeeStatic.DataType = DbType.Decimal;
				colvarFeeStatic.MaxLength = 0;
				colvarFeeStatic.AutoIncrement = false;
				colvarFeeStatic.IsNullable = false;
				colvarFeeStatic.IsPrimaryKey = false;
				colvarFeeStatic.IsForeignKey = false;
				colvarFeeStatic.IsReadOnly = false;
				colvarFeeStatic.DefaultSetting = @"";
				colvarFeeStatic.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFeeStatic);
				
				TableSchema.TableColumn colvarExchangetime = new TableSchema.TableColumn(schema);
				colvarExchangetime.ColumnName = "exchangetime";
				colvarExchangetime.DataType = DbType.Int32;
				colvarExchangetime.MaxLength = 0;
				colvarExchangetime.AutoIncrement = false;
				colvarExchangetime.IsNullable = false;
				colvarExchangetime.IsPrimaryKey = false;
				colvarExchangetime.IsForeignKey = false;
				colvarExchangetime.IsReadOnly = false;
				colvarExchangetime.DefaultSetting = @"";
				colvarExchangetime.ForeignKeyTableName = "";
				schema.Columns.Add(colvarExchangetime);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Bitcoin_Notify"].AddSchema("CurrencyCloud_Markets",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("CurrencycloudMarketKey")]
		[Bindable(true)]
		public int CurrencycloudMarketKey 
		{
			get { return GetColumnValue<int>(Columns.CurrencycloudMarketKey); }
			set { SetColumnValue(Columns.CurrencycloudMarketKey, value); }
		}
		  
		[XmlAttribute("Source")]
		[Bindable(true)]
		public int Source 
		{
			get { return GetColumnValue<int>(Columns.Source); }
			set { SetColumnValue(Columns.Source, value); }
		}
		  
		[XmlAttribute("Destination")]
		[Bindable(true)]
		public int Destination 
		{
			get { return GetColumnValue<int>(Columns.Destination); }
			set { SetColumnValue(Columns.Destination, value); }
		}
		  
		[XmlAttribute("FeePercentage")]
		[Bindable(true)]
		public decimal FeePercentage 
		{
			get { return GetColumnValue<decimal>(Columns.FeePercentage); }
			set { SetColumnValue(Columns.FeePercentage, value); }
		}
		  
		[XmlAttribute("Rate")]
		[Bindable(true)]
		public decimal? Rate 
		{
			get { return GetColumnValue<decimal?>(Columns.Rate); }
			set { SetColumnValue(Columns.Rate, value); }
		}
		  
		[XmlAttribute("Datechanged")]
		[Bindable(true)]
		public DateTime? Datechanged 
		{
			get { return GetColumnValue<DateTime?>(Columns.Datechanged); }
			set { SetColumnValue(Columns.Datechanged, value); }
		}
		  
		[XmlAttribute("FeeStatic")]
		[Bindable(true)]
		public decimal FeeStatic 
		{
			get { return GetColumnValue<decimal>(Columns.FeeStatic); }
			set { SetColumnValue(Columns.FeeStatic, value); }
		}
		  
		[XmlAttribute("Exchangetime")]
		[Bindable(true)]
		public int Exchangetime 
		{
			get { return GetColumnValue<int>(Columns.Exchangetime); }
			set { SetColumnValue(Columns.Exchangetime, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varCurrencycloudMarketKey,int varSource,int varDestination,decimal varFeePercentage,decimal? varRate,DateTime? varDatechanged,decimal varFeeStatic,int varExchangetime)
		{
			CurrencyCloudMarket item = new CurrencyCloudMarket();
			
			item.CurrencycloudMarketKey = varCurrencycloudMarketKey;
			
			item.Source = varSource;
			
			item.Destination = varDestination;
			
			item.FeePercentage = varFeePercentage;
			
			item.Rate = varRate;
			
			item.Datechanged = varDatechanged;
			
			item.FeeStatic = varFeeStatic;
			
			item.Exchangetime = varExchangetime;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varCurrencycloudMarketKey,int varSource,int varDestination,decimal varFeePercentage,decimal? varRate,DateTime? varDatechanged,decimal varFeeStatic,int varExchangetime)
		{
			CurrencyCloudMarket item = new CurrencyCloudMarket();
			
				item.CurrencycloudMarketKey = varCurrencycloudMarketKey;
			
				item.Source = varSource;
			
				item.Destination = varDestination;
			
				item.FeePercentage = varFeePercentage;
			
				item.Rate = varRate;
			
				item.Datechanged = varDatechanged;
			
				item.FeeStatic = varFeeStatic;
			
				item.Exchangetime = varExchangetime;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn CurrencycloudMarketKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn SourceColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn DestinationColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn FeePercentageColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn RateColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn DatechangedColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn FeeStaticColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn ExchangetimeColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string CurrencycloudMarketKey = @"currencycloud_market_key";
			 public static string Source = @"source";
			 public static string Destination = @"destination";
			 public static string FeePercentage = @"fee_percentage";
			 public static string Rate = @"rate";
			 public static string Datechanged = @"datechanged";
			 public static string FeeStatic = @"fee_static";
			 public static string Exchangetime = @"exchangetime";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
