using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
    /// <summary>
    /// Controller class for Errors
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ErrorXController
    {
        // Preload our schema..
        ErrorX thisSchemaLoad = new ErrorX();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ErrorXCollection FetchAll()
        {
            ErrorXCollection coll = new ErrorXCollection();
            Query qry = new Query(ErrorX.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ErrorXCollection FetchByID(object ErrorId)
        {
            ErrorXCollection coll = new ErrorXCollection().Where("error_id", ErrorId).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ErrorXCollection FetchByQuery(Query qry)
        {
            ErrorXCollection coll = new ErrorXCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ErrorId)
        {
            return (ErrorX.Delete(ErrorId) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ErrorId)
        {
            return (ErrorX.Destroy(ErrorId) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string ErrorMessage,DateTime DateCreated,int? LineNumber,string Filename)
	    {
		    ErrorX item = new ErrorX();
		    
            item.ErrorMessage = ErrorMessage;
            
            item.DateCreated = DateCreated;
            
            item.LineNumber = LineNumber;
            
            item.Filename = Filename;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string ErrorMessage,DateTime DateCreated,int? LineNumber,string Filename,int ErrorId)
	    {
		    ErrorX item = new ErrorX();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ErrorMessage = ErrorMessage;
				
			item.DateCreated = DateCreated;
				
			item.LineNumber = LineNumber;
				
			item.Filename = Filename;
				
			item.ErrorId = ErrorId;
				
	        item.Save(UserName);
	    }
    }
}
