using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
	/// <summary>
	/// Strongly-typed collection for the ErrorX class.
	/// </summary>
    [Serializable]
	public partial class ErrorXCollection : ActiveList<ErrorX, ErrorXCollection>
	{	   
		public ErrorXCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>ErrorXCollection</returns>
		public ErrorXCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                ErrorX o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Errors table.
	/// </summary>
	[Serializable]
	public partial class ErrorX : ActiveRecord<ErrorX>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public ErrorX()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public ErrorX(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public ErrorX(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public ErrorX(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Errors", TableType.Table, DataService.GetInstance("Bitcoin_Notify"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarErrorMessage = new TableSchema.TableColumn(schema);
				colvarErrorMessage.ColumnName = "error_message";
				colvarErrorMessage.DataType = DbType.String;
				colvarErrorMessage.MaxLength = 1000;
				colvarErrorMessage.AutoIncrement = false;
				colvarErrorMessage.IsNullable = false;
				colvarErrorMessage.IsPrimaryKey = false;
				colvarErrorMessage.IsForeignKey = false;
				colvarErrorMessage.IsReadOnly = false;
				colvarErrorMessage.DefaultSetting = @"";
				colvarErrorMessage.ForeignKeyTableName = "";
				schema.Columns.Add(colvarErrorMessage);
				
				TableSchema.TableColumn colvarDateCreated = new TableSchema.TableColumn(schema);
				colvarDateCreated.ColumnName = "date_created";
				colvarDateCreated.DataType = DbType.DateTime;
				colvarDateCreated.MaxLength = 0;
				colvarDateCreated.AutoIncrement = false;
				colvarDateCreated.IsNullable = false;
				colvarDateCreated.IsPrimaryKey = false;
				colvarDateCreated.IsForeignKey = false;
				colvarDateCreated.IsReadOnly = false;
				colvarDateCreated.DefaultSetting = @"";
				colvarDateCreated.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDateCreated);
				
				TableSchema.TableColumn colvarLineNumber = new TableSchema.TableColumn(schema);
				colvarLineNumber.ColumnName = "line_number";
				colvarLineNumber.DataType = DbType.Int32;
				colvarLineNumber.MaxLength = 0;
				colvarLineNumber.AutoIncrement = false;
				colvarLineNumber.IsNullable = true;
				colvarLineNumber.IsPrimaryKey = false;
				colvarLineNumber.IsForeignKey = false;
				colvarLineNumber.IsReadOnly = false;
				colvarLineNumber.DefaultSetting = @"";
				colvarLineNumber.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLineNumber);
				
				TableSchema.TableColumn colvarFilename = new TableSchema.TableColumn(schema);
				colvarFilename.ColumnName = "filename";
				colvarFilename.DataType = DbType.String;
				colvarFilename.MaxLength = 200;
				colvarFilename.AutoIncrement = false;
				colvarFilename.IsNullable = true;
				colvarFilename.IsPrimaryKey = false;
				colvarFilename.IsForeignKey = false;
				colvarFilename.IsReadOnly = false;
				colvarFilename.DefaultSetting = @"";
				colvarFilename.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFilename);
				
				TableSchema.TableColumn colvarErrorId = new TableSchema.TableColumn(schema);
				colvarErrorId.ColumnName = "error_id";
				colvarErrorId.DataType = DbType.Int32;
				colvarErrorId.MaxLength = 0;
				colvarErrorId.AutoIncrement = true;
				colvarErrorId.IsNullable = false;
				colvarErrorId.IsPrimaryKey = true;
				colvarErrorId.IsForeignKey = false;
				colvarErrorId.IsReadOnly = false;
				colvarErrorId.DefaultSetting = @"";
				colvarErrorId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarErrorId);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Bitcoin_Notify"].AddSchema("Errors",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("ErrorMessage")]
		[Bindable(true)]
		public string ErrorMessage 
		{
			get { return GetColumnValue<string>(Columns.ErrorMessage); }
			set { SetColumnValue(Columns.ErrorMessage, value); }
		}
		  
		[XmlAttribute("DateCreated")]
		[Bindable(true)]
		public DateTime DateCreated 
		{
			get { return GetColumnValue<DateTime>(Columns.DateCreated); }
			set { SetColumnValue(Columns.DateCreated, value); }
		}
		  
		[XmlAttribute("LineNumber")]
		[Bindable(true)]
		public int? LineNumber 
		{
			get { return GetColumnValue<int?>(Columns.LineNumber); }
			set { SetColumnValue(Columns.LineNumber, value); }
		}
		  
		[XmlAttribute("Filename")]
		[Bindable(true)]
		public string Filename 
		{
			get { return GetColumnValue<string>(Columns.Filename); }
			set { SetColumnValue(Columns.Filename, value); }
		}
		  
		[XmlAttribute("ErrorId")]
		[Bindable(true)]
		public int ErrorId 
		{
			get { return GetColumnValue<int>(Columns.ErrorId); }
			set { SetColumnValue(Columns.ErrorId, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varErrorMessage,DateTime varDateCreated,int? varLineNumber,string varFilename)
		{
			ErrorX item = new ErrorX();
			
			item.ErrorMessage = varErrorMessage;
			
			item.DateCreated = varDateCreated;
			
			item.LineNumber = varLineNumber;
			
			item.Filename = varFilename;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(string varErrorMessage,DateTime varDateCreated,int? varLineNumber,string varFilename,int varErrorId)
		{
			ErrorX item = new ErrorX();
			
				item.ErrorMessage = varErrorMessage;
			
				item.DateCreated = varDateCreated;
			
				item.LineNumber = varLineNumber;
			
				item.Filename = varFilename;
			
				item.ErrorId = varErrorId;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn ErrorMessageColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn DateCreatedColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn LineNumberColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn FilenameColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn ErrorIdColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string ErrorMessage = @"error_message";
			 public static string DateCreated = @"date_created";
			 public static string LineNumber = @"line_number";
			 public static string Filename = @"filename";
			 public static string ErrorId = @"error_id";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
