using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
    /// <summary>
    /// Controller class for Markets_Static
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class MarketsStaticController
    {
        // Preload our schema..
        MarketsStatic thisSchemaLoad = new MarketsStatic();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public MarketsStaticCollection FetchAll()
        {
            MarketsStaticCollection coll = new MarketsStaticCollection();
            Query qry = new Query(MarketsStatic.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public MarketsStaticCollection FetchByID(object MarketStaticKey)
        {
            MarketsStaticCollection coll = new MarketsStaticCollection().Where("market_static_key", MarketStaticKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public MarketsStaticCollection FetchByQuery(Query qry)
        {
            MarketsStaticCollection coll = new MarketsStaticCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MarketStaticKey)
        {
            return (MarketsStatic.Delete(MarketStaticKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MarketStaticKey)
        {
            return (MarketsStatic.Destroy(MarketStaticKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? SourceCurrency,int? DestinationCurrency,decimal? FeePercentage,decimal? FeeStatic,int? ExchangeKey,string Apicall)
	    {
		    MarketsStatic item = new MarketsStatic();
		    
            item.SourceCurrency = SourceCurrency;
            
            item.DestinationCurrency = DestinationCurrency;
            
            item.FeePercentage = FeePercentage;
            
            item.FeeStatic = FeeStatic;
            
            item.ExchangeKey = ExchangeKey;
            
            item.Apicall = Apicall;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int MarketStaticKey,int? SourceCurrency,int? DestinationCurrency,decimal? FeePercentage,decimal? FeeStatic,int? ExchangeKey,string Apicall)
	    {
		    MarketsStatic item = new MarketsStatic();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MarketStaticKey = MarketStaticKey;
				
			item.SourceCurrency = SourceCurrency;
				
			item.DestinationCurrency = DestinationCurrency;
				
			item.FeePercentage = FeePercentage;
				
			item.FeeStatic = FeeStatic;
				
			item.ExchangeKey = ExchangeKey;
				
			item.Apicall = Apicall;
				
	        item.Save(UserName);
	    }
    }
}
