using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
    /// <summary>
    /// Controller class for Path_Routes
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class PathRouteController
    {
        // Preload our schema..
        PathRoute thisSchemaLoad = new PathRoute();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public PathRouteCollection FetchAll()
        {
            PathRouteCollection coll = new PathRouteCollection();
            Query qry = new Query(PathRoute.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public PathRouteCollection FetchByID(object PathRouteKey)
        {
            PathRouteCollection coll = new PathRouteCollection().Where("path_route_key", PathRouteKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public PathRouteCollection FetchByQuery(Query qry)
        {
            PathRouteCollection coll = new PathRouteCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object PathRouteKey)
        {
            return (PathRoute.Delete(PathRouteKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object PathRouteKey)
        {
            return (PathRoute.Destroy(PathRouteKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int PathKey,int MarketKey)
	    {
		    PathRoute item = new PathRoute();
		    
            item.PathKey = PathKey;
            
            item.MarketKey = MarketKey;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int PathRouteKey,int PathKey,int MarketKey)
	    {
		    PathRoute item = new PathRoute();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.PathRouteKey = PathRouteKey;
				
			item.PathKey = PathKey;
				
			item.MarketKey = MarketKey;
				
	        item.Save(UserName);
	    }
    }
}
