using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
    /// <summary>
    /// Controller class for Settings
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SettingController
    {
        // Preload our schema..
        Setting thisSchemaLoad = new Setting();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SettingCollection FetchAll()
        {
            SettingCollection coll = new SettingCollection();
            Query qry = new Query(Setting.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SettingCollection FetchByID(object PercentageThreashold)
        {
            SettingCollection coll = new SettingCollection().Where("Percentage_Threashold", PercentageThreashold).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SettingCollection FetchByQuery(Query qry)
        {
            SettingCollection coll = new SettingCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object PercentageThreashold)
        {
            return (Setting.Delete(PercentageThreashold) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object PercentageThreashold)
        {
            return (Setting.Destroy(PercentageThreashold) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(decimal PercentageThreashold)
	    {
		    Setting item = new Setting();
		    
            item.PercentageThreashold = PercentageThreashold;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(decimal PercentageThreashold)
	    {
		    Setting item = new Setting();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.PercentageThreashold = PercentageThreashold;
				
	        item.Save(UserName);
	    }
    }
}
