using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
	/// <summary>
	/// Strongly-typed collection for the Setting class.
	/// </summary>
    [Serializable]
	public partial class SettingCollection : ActiveList<Setting, SettingCollection>
	{	   
		public SettingCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>SettingCollection</returns>
		public SettingCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                Setting o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Settings table.
	/// </summary>
	[Serializable]
	public partial class Setting : ActiveRecord<Setting>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public Setting()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public Setting(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public Setting(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public Setting(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Settings", TableType.Table, DataService.GetInstance("Bitcoin_Notify"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarPercentageThreashold = new TableSchema.TableColumn(schema);
				colvarPercentageThreashold.ColumnName = "Percentage_Threashold";
				colvarPercentageThreashold.DataType = DbType.Decimal;
				colvarPercentageThreashold.MaxLength = 0;
				colvarPercentageThreashold.AutoIncrement = false;
				colvarPercentageThreashold.IsNullable = false;
				colvarPercentageThreashold.IsPrimaryKey = true;
				colvarPercentageThreashold.IsForeignKey = false;
				colvarPercentageThreashold.IsReadOnly = false;
				colvarPercentageThreashold.DefaultSetting = @"";
				colvarPercentageThreashold.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPercentageThreashold);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Bitcoin_Notify"].AddSchema("Settings",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("PercentageThreashold")]
		[Bindable(true)]
		public decimal PercentageThreashold 
		{
			get { return GetColumnValue<decimal>(Columns.PercentageThreashold); }
			set { SetColumnValue(Columns.PercentageThreashold, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(decimal varPercentageThreashold)
		{
			Setting item = new Setting();
			
			item.PercentageThreashold = varPercentageThreashold;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(decimal varPercentageThreashold)
		{
			Setting item = new Setting();
			
				item.PercentageThreashold = varPercentageThreashold;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn PercentageThreasholdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string PercentageThreashold = @"Percentage_Threashold";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
