using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
    /// <summary>
    /// Controller class for Exchanges
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ExchangeController
    {
        // Preload our schema..
        Exchange thisSchemaLoad = new Exchange();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ExchangeCollection FetchAll()
        {
            ExchangeCollection coll = new ExchangeCollection();
            Query qry = new Query(Exchange.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ExchangeCollection FetchByID(object ExchangeKey)
        {
            ExchangeCollection coll = new ExchangeCollection().Where("exchange_key", ExchangeKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ExchangeCollection FetchByQuery(Query qry)
        {
            ExchangeCollection coll = new ExchangeCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ExchangeKey)
        {
            return (Exchange.Delete(ExchangeKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ExchangeKey)
        {
            return (Exchange.Destroy(ExchangeKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int ExchangeKey,string ExchangeName,string ExchangeShortname,bool? Onlyalt,decimal? FeePercentage,decimal? WithdrawlFee,bool? Isstatic)
	    {
		    Exchange item = new Exchange();
		    
            item.ExchangeKey = ExchangeKey;
            
            item.ExchangeName = ExchangeName;
            
            item.ExchangeShortname = ExchangeShortname;
            
            item.Onlyalt = Onlyalt;
            
            item.FeePercentage = FeePercentage;
            
            item.WithdrawlFee = WithdrawlFee;
            
            item.Isstatic = Isstatic;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int ExchangeKey,string ExchangeName,string ExchangeShortname,bool? Onlyalt,decimal? FeePercentage,decimal? WithdrawlFee,bool? Isstatic)
	    {
		    Exchange item = new Exchange();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ExchangeKey = ExchangeKey;
				
			item.ExchangeName = ExchangeName;
				
			item.ExchangeShortname = ExchangeShortname;
				
			item.Onlyalt = Onlyalt;
				
			item.FeePercentage = FeePercentage;
				
			item.WithdrawlFee = WithdrawlFee;
				
			item.Isstatic = Isstatic;
				
	        item.Save(UserName);
	    }
    }
}
