using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
    /// <summary>
    /// Controller class for Exchange_Currency
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ExchangeCurrencyController
    {
        // Preload our schema..
        ExchangeCurrency thisSchemaLoad = new ExchangeCurrency();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ExchangeCurrencyCollection FetchAll()
        {
            ExchangeCurrencyCollection coll = new ExchangeCurrencyCollection();
            Query qry = new Query(ExchangeCurrency.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ExchangeCurrencyCollection FetchByID(object ExchangeCurrencyKey)
        {
            ExchangeCurrencyCollection coll = new ExchangeCurrencyCollection().Where("exchange_currency_key", ExchangeCurrencyKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ExchangeCurrencyCollection FetchByQuery(Query qry)
        {
            ExchangeCurrencyCollection coll = new ExchangeCurrencyCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ExchangeCurrencyKey)
        {
            return (ExchangeCurrency.Delete(ExchangeCurrencyKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ExchangeCurrencyKey)
        {
            return (ExchangeCurrency.Destroy(ExchangeCurrencyKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int ExchangeCurrencyKey,int ExchangeKey,int Currency)
	    {
		    ExchangeCurrency item = new ExchangeCurrency();
		    
            item.ExchangeCurrencyKey = ExchangeCurrencyKey;
            
            item.ExchangeKey = ExchangeKey;
            
            item.Currency = Currency;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int ExchangeCurrencyKey,int ExchangeKey,int Currency)
	    {
		    ExchangeCurrency item = new ExchangeCurrency();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ExchangeCurrencyKey = ExchangeCurrencyKey;
				
			item.ExchangeKey = ExchangeKey;
				
			item.Currency = Currency;
				
	        item.Save(UserName);
	    }
    }
}
