using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Bitcoin_Notify_DB
{
    /// <summary>
    /// Controller class for Update_Recurring
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class UpdateRecurringController
    {
        // Preload our schema..
        UpdateRecurring thisSchemaLoad = new UpdateRecurring();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public UpdateRecurringCollection FetchAll()
        {
            UpdateRecurringCollection coll = new UpdateRecurringCollection();
            Query qry = new Query(UpdateRecurring.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public UpdateRecurringCollection FetchByID(object ContinueX)
        {
            UpdateRecurringCollection coll = new UpdateRecurringCollection().Where("continue", ContinueX).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public UpdateRecurringCollection FetchByQuery(Query qry)
        {
            UpdateRecurringCollection coll = new UpdateRecurringCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ContinueX)
        {
            return (UpdateRecurring.Delete(ContinueX) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ContinueX)
        {
            return (UpdateRecurring.Destroy(ContinueX) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(bool ContinueX)
	    {
		    UpdateRecurring item = new UpdateRecurring();
		    
            item.ContinueX = ContinueX;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(bool ContinueX)
	    {
		    UpdateRecurring item = new UpdateRecurring();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ContinueX = ContinueX;
				
	        item.Save(UserName);
	    }
    }
}
